export const RESOURCE_SET_OPTION_TIME_START = 'RESOURCE_SET_OPTION_TIME_START'
export const RESOURCE_SET_OPTION_TIME_END = 'RESOURCE_SET_OPTION_TIME_END'
export const RESOURCE_SET_OPTION_INTERVAL = 'RESOURCE_SET_OPTION_INTERVAL'